### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ImDini** [QWERTxD/BetterDiscordPlugins#106]
This plugin causes crashes with latest discord updates (yes and latest better discord update). I finally found out which plugin it is because it's only when I'm trying to quickly message someone (CTRL + K). After disabling "quick toggler" I no longer crash

**Comment by IFD3** [comment]
having the same problem, CTRL+D = instant crash.

**Comment by Technetium1** [comment]
@QWERTxD In the case it gets fixed here's a traceback

The `.length` being undefined here is what throws the error:
https://github.com/QWERTxD/BetterDiscordPlugins/blob/5739e38be0861498f15ef76f1776cb75f0f6a304/QuickToggler/QuickToggler.plugin.js#L645

```
[CrashRecovery] HEY OVER HERE! Show this to the plugin developer or in the support server!
Prettified stacktraces, stack:
 TypeError: Cannot read property 'length' of undefined
    at algorithm (betterdiscord://plugins/QuickToggler.plugin.js:646:42)
    at Object.go (betterdiscord://plugins/QuickToggler.plugin.js:335:31)
    at sortByBestResults (betterdiscord://plugins/QuickToggler.plugin.js:1134:39)
    at Results (betterdiscord://plugins/QuickToggler.plugin.js:1154:21) 
Component stack:
     at Results (betterdiscord://plugins/QuickToggler.plugin.js:1148:5)
    at h (https://discord.com/assets/2558d62….js:2159:442)
    at div
    at https://discord.com/assets/2558d62….js:3670:11
    at div
    at h (https://discord.com/assets/2558d62….js:2159:442)
    at div
    at https://discord.com/assets/2558d62….js:248:527
    at h (https://discord.com/assets/2558d62….js:2159:442)
    at div
    at https://discord.com/assets/2558d62….js:3394:452
    at P (https://discord.com/assets/2558d62….js:3571:628)
    at QuickToggler_QuickToggler (betterdiscord://plugins/QuickToggler.plugin.js:1188:6)
    at div
    at S (https://discord.com/assets/2558d62….js:3542:206)
    at AppLayer
    at t (https://discord.com/assets/2558d62….js:3576:655)
    at t (https://discord.com/assets/2558d62….js:4476:162)
    at R (https://discord.com/assets/2558d62….js:3578:74)
    at t (https://discord.com/assets/2558d62….js:3541:407)
    at VerificationLayerProvider
    at E (https://discord.com/assets/2558d62….js:2430:707)
    at t (https://discord.com/assets/2558d62….js:3541:407)
    at AppLayerProvider
    at _ (https://discord.com/assets/2558d62….js:1722:679)
    at h (https://discord.com/assets/2558d62….js:2159:442)
    at t (https://discord.com/assets/2558d62….js:796:543)
    at v (https://discord.com/assets/2558d62….js:799:969)
    at t (https://discord.com/assets/2558d62….js:800:445)
    at u (https://discord.com/assets/2558d62….js:4135:826)
    at T (https://discord.com/assets/2558d62….js:780:819)
    at ne (https://discord.com/assets/2558d62….js:784:312)
    at t (https://discord.com/assets/2558d62….js:841:63)
    at u (https://discord.com/assets/2558d62….js:4134:705)
    at https://discord.com/assets/2558d62….js:4640:30
    at H (https://discord.com/assets/2558d62….js:5782:700)
    at t (https://discord.com/assets/2558d62….js:5965:570)
    at t (https://discord.com/assets/2558d62….js:5921:817)
    at f (https://discord.com/assets/2558d62….js:2470:672)
```
