### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lukethesaint** [QWERTxD/BetterDiscordPlugins#294]
**Describe the Bug**

Issue installing the plugin.
**To Reproduce**

Dragging the file in the plugin folder.
**Expected Behavior**

A message prompt appears with an error message.
**Screenshots**

TypeError: Cannot read property 'ChannelTypes' of undefined
    at eval (betterdiscord://plugins/InAppNotifications.plugin.js:208:50)
    at eval (betterdiscord://plugins/InAppNotifications.plugin.js:1009:7)
    at Object.requireAddon (<anonymous>:4:43438)
    at Object.loadAddon (<anonymous>:4:9197)
    at Object.loadAddon (<anonymous>:4:41165)
    at AsyncFunction.<anonymous> (<anonymous>:4:7353)
**Discord Version**

Stable
**Additional Context**

**Comment by fowlis** [comment]
The plugin was updated yesterday. Try redownloading it.
