### ISSUE TITLE
QuickMessages not showing settings

### ISSUE THREAD

**Issue by lyratcm** [QWERTxD/BetterDiscordPlugins#308]
Just installed the pugin and restarted discord but can't open setting to edit anything (can't get the option to save/past as well)

trying to open the setting give this error
![image](https://user-images.githubusercontent.com/13206890/196270090-c16e9e7f-4567-4cfb-8bec-b106f3e3f1d3.png)

and the console the console prints this:
[2022-10-17 19:52:08.879][CONSOLE:ERROR] Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at nc (https://discord.com/assets/ab46f87faa301aa65b5b.js:1557:686)
    at e (https://discord.com/assets/ab46f87faa301aa65b5b.js:1496:659)
    at Va (https://discord.com/assets/ab46f87faa301aa65b5b.js:1508:702)
    at $s (https://discord.com/assets/ab46f87faa301aa65b5b.js:1553:916)
    at ku (https://discord.com/assets/ab46f87faa301aa65b5b.js:1543:748)
    at Uu (https://discord.com/assets/ab46f87faa301aa65b5b.js:1543:676)
    at wu (https://discord.com/assets/ab46f87faa301aa65b5b.js:1543:539)
    at yu (https://discord.com/assets/ab46f87faa301aa65b5b.js:1540:164)
    at https://discord.com/assets/ab46f87faa301aa65b5b.js:1485:340
    at t.unstable_runWithPriority (https://discord.com/assets/ab46f87faa301aa65b5b.js:1663:828)
    at Ko (https://discord.com/assets/ab46f87faa301aa65b5b.js:1485:117)
    at Xo (https://discord.com/assets/ab46f87faa301aa65b5b.js:1485:285)
    at qo (https://discord.com/assets/ab46f87faa301aa65b5b.js:1485:220)
    at we (https://discord.com/assets/ab46f87faa301aa65b5b.js:1562:198)
    at en (https://discord.com/assets/ab46f87faa301aa65b5b.js:1462:800)
    at HTMLDivElement.r (https://discord.com/assets/753cd3ba2f8a95f7e3fe.js:145:559)

better discord v1.8.1
quickmessages 1.2.5

**Comment by lyratcm** [comment]
This has actually been fixed in betterdiscord 1.8.2 for me
