### ISSUE TITLE
AssignBadges is not working

### ISSUE THREAD

**Issue by Hawchek** [QWERTxD/BetterDiscordPlugins#323]
I have this error message

TypeError: Cannot destructure property 'BadgeKeys' of 'external_PluginApi_namespaceObject.WebpackModules.getByProps(...)' as it is undefined.
    at eval (betterdiscord://plugins/AssignBadges.plugin.js:337:5)
    at eval (betterdiscord://plugins/AssignBadges.plugin.js:719:5)
    at buildPlugin (betterdiscord://plugins/AssignBadges.plugin.js:721:4)
    at eval (betterdiscord://plugins/AssignBadges.plugin.js:726:2)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at Object.reloadAddon (<anonymous>:4:10053)
    at AsyncFunction.<anonymous> (<anonymous>:4:7189)

**Comment by skyedoesgaming** [comment]
Discord updated, and QWERT stopped updating his plugins. Most likely won't be fixed for a while.

**Comment by hanicsgo** [comment]
i tried add 
			}, {
				id: "ACTIVE_DEVELOPER",
				value: UserFlags["ACTIVE_DEVELOPER"],
				name: "Active Developer",
				key: BadgeKeys["ACTIVE_DEVELOPER"]
				
but i think u should wait him update KPI discord
