### ISSUE TITLE
[BUG] CopyRoleColors - Cannot Compile

### ISSUE THREAD

**Issue by ConaII** [QWERTxD/BetterDiscordPlugins#337]
**Describe the Bug**
This bugs happens in the latest BetterDiscord version.

**Error log**
```
TypeError: Cannot read property 'MemberRole' of undefined
    at eval (betterdiscord://plugins/CopyRoleColors.plugin.js:78:65)
    at eval (betterdiscord://plugins/CopyRoleColors.plugin.js:126:7)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at Object.loadAllAddons (<anonymous>:4:11637)
    at Object.initialize (<anonymous>:4:6059)
    at Object.initialize (<anonymous>:4:36059)
    at Object.startup (<anonymous>:4:396505)
```

**Comment by CodyDaniel1** [comment]
any update on this?
