### ISSUE TITLE
[BUG] UserVolumeBooster ZeresPluginLibrary not found

### ISSUE THREAD

**Issue by Tsagu** [QWERTxD/BetterDiscordPlugins#338]
As title says, UserVolumeBooster says it will not work becasue ZeresPluginLibrary was not found. I have ZeresPlugin installed, up to date on both plugins, and enabled. 
![image](https://user-images.githubusercontent.com/17733711/205715681-0ddd6c64-2276-4e80-9945-45e8f1f94675.png)

**Comment by Tsagu** [comment]
Fenpai
#1682
TypeError: Cannot read property 'prototype' of undefined
    at Plugin.patch (betterdiscord://plugins/UserVolumeBooster.plugin.js:322:36)
    at Plugin.start (betterdiscord://plugins/UserVolumeBooster.plugin.js:315:10)
    at Object.startPlugin (<anonymous>:4:39650)
    at Object.startAddon (<anonymous>:4:39443)
    at Object.loadAddon (<anonymous>:4:9557)
    at Object.loadAddon (<anonymous>:4:36864)
    at Object.loadAllAddons (<anonymous>:4:11637)
    at Object.initialize (<anonymous>:4:6059)
    at Object.initialize (<anonymous>:4:36059)
    at Object.startup (<anonymous>:4:396505)
