### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by aqtsalt** [QWERTxD/BetterDiscordPlugins#339]
**Describe the Bug**

`TypeError: Cannot destructure property 'BadgeKeys' of 'external_PluginApi_namespaceObject.WebpackModules.getByProps(...)' as it is undefined.
    at eval (betterdiscord://plugins/AssignBadges.plugin.js:338:5)
    at eval (betterdiscord://plugins/AssignBadges.plugin.js:776:5)
    at buildPlugin (betterdiscord://plugins/AssignBadges.plugin.js:778:4)
    at eval (betterdiscord://plugins/AssignBadges.plugin.js:783:2)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at Object.loadAllAddons (<anonymous>:4:11637)
    at Object.initialize (<anonymous>:4:6059)
    at Object.initialize (<anonymous>:4:36059)
    at Object.startup (<anonymous>:4:396505)`
**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by aqtsalt** [comment]
@QWERTxD please fix asap

**Comment by dudeisbrendan03** [comment]
Came across this today, I'll try to be a bit more descriptive ;)

AssignBadges v1.0.27
Discord Canary 167790 (9a1e87f)
Host 1.0.55 (28450)
Windows 11 Enterprise (Insiders Edition) 64-Bit (10.0.25247)

Using Fluent 1.0.13 with the following plugins:
```sh
BDFDB
# AssignBadges off
BetterAnimations
BetterDiscord TogetherV2
BetterFormattingRedux
BetterInvites
# BetterMessageLinks off
BetterRoleColors
BetterSyntax
# BiggerStreamPreview off
CallTimeCounter
ChannelDms
ChannelsPreview
ClickableMentions
CollapsibleUI
DoubleClickToEdit
FavoriteMedia
FileViewer
# GlobalReplies off
# GuildProfile off
HideChannels
ImageUtilities
InvisibleTyping
PasscodeLock
PermissionsViewer
PinDMs
PinIcon
PluginRepo
QuickMention
# SendTimestamps off
ShowAllActivities
ShowBadgesInChat
ShowConnections
SplitLargeMessages
SpotifyControls
StaffTag
Translator
TypingUsersAvatars
ZeresPluginLibrary
```

Can't appear to find `BadgeKeys` prop, going to see if Fluent, BetterBadges or ShowBadgesInChat changes anything, will update to say if I found something disabling my extensions now

**Comment by dudeisbrendan03** [comment]
Unloaded all extensions and themes, still won't load. Maybe something to do with the latest build?
