### ISSUE TITLE
[BUG] CopyRoleColors doesnt work

### ISSUE THREAD

**Issue by fabidnl** [QWERTxD/BetterDiscordPlugins#347]
there is the following error:

TypeError: Cannot read property 'MemberRole' of undefined
    at eval (betterdiscord://plugins/CopyRoleColors.plugin.js:78:65)
    at eval (betterdiscord://plugins/CopyRoleColors.plugin.js:126:7)
    at Object.requireAddon (<anonymous>:4:37112)
    at Object.loadAddon (<anonymous>:4:8234)
    at Object.loadAddon (<anonymous>:4:34784)
    at AsyncFunction.<anonymous> (<anonymous>:4:6226)

**Comment by CodyDaniel1** [comment]
any update on this?
