### ISSUE TITLE
Errorwhilst enabling the plugin

### ISSUE THREAD

**Issue by mooncoders-dev** [QWERTxD/BetterDiscordPlugins#348]
**Describe the Bug**

TypeError: Cannot destructure property 'BadgeKeys' of 'external_PluginApi_namespaceObject.WebpackModules.getByProps(...)' as it is undefined.
    at eval (betterdiscord://plugins/AssignBadges.plugin.js:337:5)
    at eval (betterdiscord://plugins/AssignBadges.plugin.js:719:5)
    at buildPlugin (betterdiscord://plugins/AssignBadges.plugin.js:721:4)
    at eval (betterdiscord://plugins/AssignBadges.plugin.js:726:2)
    at Object.requireAddon (<anonymous>:4:37112)
    at Object.loadAddon (<anonymous>:4:8234)
    at Object.loadAddon (<anonymous>:4:34784)
    at AsyncFunction.<anonymous> (<anonymous>:4:6226)
**To Reproduce**

**Expected Behavior**

I droped the plugin into the plugins folder and got the error

**Screenshots**

![image](https://user-images.githubusercontent.com/108657960/210425875-a211c1be-257e-43ba-a7e4-8391259c6a5a.png)

**Discord Version**

Stable 165485 (07d8b41) Host 1.0.9008 (27798) Windows 10 64-Bit (10.0.22621)
**Additional Context**

**Comment by lYdFiRe** [comment]
I have the exact same issue

**Comment by kruasann** [comment]
I have the exact same issue

**Comment by dudeisbrendan03** [comment]
Duplicate #345, unless someone can confirm this still works, might be dead, something somewhere has probably just been renamed or moved

**Comment by Wall234** [comment]
Same issue
