### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dropalways** [QWERTxD/BetterDiscordPlugins#360]
TypeError: Cannot destructure property 'ComponentDispatch' of 'getByProps(...)' as it is undefined.
    at eval (betterdiscord://plugins/GrammarCorrect.plugin.js:329:4)
    at buildPlugin (betterdiscord://plugins/GrammarCorrect.plugin.js:420:4)
    at eval (betterdiscord://plugins/GrammarCorrect.plugin.js:425:2)
    at Object.requireAddon (<anonymous>:4:37112)
    at Object.loadAddon (<anonymous>:4:8234)
    at Object.loadAddon (<anonymous>:4:34784)
    at Object.reloadAddon (<anonymous>:4:9124)
    at AsyncFunction.<anonymous> (<anonymous>:4:6260)
    
    Cannot compile
    
    Stable

**Comment by ELLIOTTCABLE** [comment]
A better title, and using ` ```code``` ` blocks in the description, would be helpful. (=
