### ISSUE TITLE
Assign Badgets error

### ISSUE THREAD

**Issue by moon-development-de** [QWERTxD/BetterDiscordPlugins#365]
TypeError: Cannot destructure property 'BadgeKeys' of 'external_PluginApi_namespaceObject.WebpackModules.getByProps(...)' as it is undefined.
    at eval (betterdiscord://plugins/AssignBadges.plugin.js:337:5)
    at eval (betterdiscord://plugins/AssignBadges.plugin.js:719:5)
    at buildPlugin (betterdiscord://plugins/AssignBadges.plugin.js:721:4)
    at eval (betterdiscord://plugins/AssignBadges.plugin.js:726:2)
    at x.requireAddon (<anonymous>:4:37871)
    at x.loadAddon (<anonymous>:4:8814)
    at x.loadAddon (<anonymous>:4:35543)
    at x.loadAllAddons (<anonymous>:4:11288)
    at x.initialize (<anonymous>:4:5710)
    at x.initialize (<anonymous>:4:34738)
    at Object.startup (<anonymous>:4:392305)

**Comment by dusan-till** [comment]
I get a similar error on BetterDiscord `1.9.2` and Discord stable `0.0.25`

**Comment by M-nsieur** [comment]
I have the exact same error
