### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by president-E** [QWERTxD/BetterDiscordPlugins#366]
TypeError: Cannot destructure property 'BadgeKeys' of 'external_PluginApi_namespaceObject.WebpackModules.getByProps(...)' as it is undefined.
    at eval (betterdiscord://plugins/AssignBadges.plugin.js:337:5)
    at eval (betterdiscord://plugins/AssignBadges.plugin.js:719:5)
    at buildPlugin (betterdiscord://plugins/AssignBadges.plugin.js:721:4)
    at eval (betterdiscord://plugins/AssignBadges.plugin.js:726:2)
    at Object.requireAddon (<anonymous>:4:37871)
    at Object.loadAddon (<anonymous>:4:8814)
    at Object.loadAddon (<anonymous>:4:35543)
    at AsyncFunction.<anonymous> (<anonymous>:4:6806)

**Comment by Noxillio** [comment]
Same problem here.

**Comment by Ikstoi** [comment]
Same

**Comment by anastazialol** [comment]
Y'all retarded that's why.
