### ISSUE TITLE
[BUG] New discord update broke the plugin

### ISSUE THREAD

**Issue by roller59** [QWERTxD/BetterDiscordPlugins#396]
The new update made the plugin unusable, just getting the notif that it cant start. Also are there any alternatives to it by any chance? Thnaks in advance

**Comment by thehamish555** [comment]
i made a pull request that has a fix for this made by someone on reddit, seems to work
#397

**Comment by roller59** [comment]
> i made a pull request that has a fix for this made by someone on reddit, seems to work #397

Thank you so much

**Comment by Czerwony150** [comment]
I don't know about others but in my case this plugin doesn't turn on when starting DSC. When trying to turn it off, it shows information that it can't be stopped and only re-enabling it helps.

**Comment by Leah96xxx** [comment]
InAppNotifications seems to have mostly been working for me, only giving a "can't start" notification at the same time as an actual notification whenever one was received, but today it just started repeatedly spamming me with the error non-stop.

Console shows this:
```
[InAppNotifications] Error! TypeError: Cannot read properties of undefined (reading 'isRawMessageMentioned')
    at plugin.supposedToNotify (VM579 InAppNotifications.plugin.js:998:50)
    at plugin.onMessage (VM579 InAppNotifications.plugin.js:811:21)
    at onMessage (VM579 InAppNotifications.plugin.js:599:15)
    at web.fbc721351be4d1055a8c.js:12:9580678
    at Set.forEach (<anonymous>)
    at web.fbc721351be4d1055a8c.js:12:9580667
    at web.fbc721351be4d1055a8c.js:12:9587105
    at h._dispatch (web.fbc721351be4d1055a8c.js:12:9580640)
    at web.fbc721351be4d1055a8c.js:12:9580152
    at l.log (web.fbc721351be4d1055a8c.js:12:9587047)
    at h._dispatchWithLogging (web.fbc721351be4d1055a8c.js:12:9580094)
    at h._dispatchWithDevtools (web.fbc721351be4d1055a8c.js:12:9579670)
    at Object.dispatch_MESSAGE_CREATE [as MESSAGE_CREATE] (web.fbc721351be4d1055a8c.js:12:9578984)
    at web.fbc721351be4d1055a8c.js:12:9579085
    at h.flushWaitQueue (web.fbc721351be4d1055a8c.js:12:9579566)
    at web.fbc721351be4d1055a8c.js:12:9579115
    at new Promise (<anonymous>)
    at h.dispatch (web.fbc721351be4d1055a8c.js:12:9578864)
    at h.dispatch (renderer.js:5:22880)
    at F (web.fbc721351be4d1055a8c.js:12:6131169)
    at Object.dispatch (web.fbc721351be4d1055a8c.js:12:6136904)
    at h.dispatchOne (web.fbc721351be4d1055a8c.js:12:6116972)
    at web.fbc721351be4d1055a8c.js:12:6115996
    at Array.forEach (<anonymous>)
    at web.fbc721351be4d1055a8c.js:12:6115951
    at e.batched (web.fbc721351be4d1055a8c.js:12:9584725)
    at h.dispatchMultiple (web.fbc721351be4d1055a8c.js:12:6115936)
    at flush (web.fbc721351be4d1055a8c.js:12:6117764)
    at E (sentry.47d15323f97d35a729c1.js:1:618129)
```

I tried the version in PR #398 and it seems to resolve the issue. Haven't tried #397

**Comment by nalathethird** [comment]
agree on this, i havent seen this working since a large update a few weeks ago...
recently just had it spam me, *I dont work* messages and to join the discord for help, but you cant even click on it... :/

**Comment by thehamish555** [comment]
> I tried the version in PR #398 and it seems to resolve the issue. Haven't tried #397

I have been using #398 since it came out, my PR was temporary thing that can be ignored, I just left it open incase the developers wanted to look into other approaches.
